sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull lacledeslan/gamesvr-warsow

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-warsow-freeplay --tag lacledeslan/gamesvr-warsow-freeplay --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" -f Dockerfile.linux .
  - docker run -it --rm lltest/gamesvr-warsow-freeplay ./ll-tests/gamesvr-warsow-freeplay.sh

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-warsow-freeplay
  on:
    branch: master
